server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ait159..
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.200.130
    port: 6379