server:
  port: 9527

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: 10.21.22.100:8848
        group: DEFAULT_GROUP

    gateway:
      routes:
        - id: user_routh
          uri: lb://user-service
          predicates:
            - Path=/user/**


  datasource:
    url: jdbc:mysql://10.21.22.100:10011/atvv-im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&allowMultiQueries=true
    username: root
    password: mp123456*.*
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.21.22.100
    port: 6380
    password: ATVV123456*.*