server:
  port: 9527

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
        group: ${NACOS_GROUP}

    gateway:
      routes:
        - id: user_routh
          uri: lb://user-service
          predicates:
            - Path=/user/**


  datasource:
    url: jdbc:mysql://${MYSQL_ADDR}:${MYSQL_PORT}/${MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&allowMultiQueries=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_ADDR}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}